import type { Metadata } from "next";
import { Unbounded, Manrope, Open_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { AnalysisModal } from "@/components/custom/AnalysisModal";

const unbounded = Unbounded({
  subsets: ["cyrillic", "latin"],
  variable: "--font-unbounded", // Создаем CSS-переменную
});

const manrope = Manrope({
  subsets: ["cyrillic", "latin"],
  variable: "--font-manrope",
});

const openSans = Open_Sans({
  subsets: ["cyrillic", "latin"],
  variable: "--font-open-sans", // CSS-переменная для Tailwind
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={`${unbounded.variable} ${manrope.variable} ${openSans.variable}`}>
      <body className="flex flex-col min-h-screen">
        <Header />
        {/* Центрируем основной контент так же, как Header и Footer */}
        <main className="container grow pb-14 pt-4">
          {children}
        </main>
        <Footer />
        <AnalysisModal />
      </body>
    </html>
  );
}
