import type { Metadata } from "next";
import { Unbounded, Manrope, Open_Sans, Inter } from "next/font/google";
import "@/app/globals.css";
import { Header } from "@/components/layout/header/Header";
import { Footer } from "@/components/layout/Footer";
import { AnalysisModal } from "@/components/custom/AnalysisModal";
import { AuthModal } from "@/components/custom/Auth/AuthModal";
import { DesktopGuard } from "@/components/custom/DesktopGuard";

const unbounded = Unbounded({
  subsets: ["cyrillic", "latin"],
  variable: "--font-unbounded", // Создаем CSS-переменную
});

const inter = Inter({
  subsets: ["cyrillic", "latin"],
  variable: "--font-inter",
})

const manrope = Manrope({
  subsets: ["cyrillic", "latin"],
  variable: "--font-manrope",
});

const openSans = Open_Sans({
  subsets: ["cyrillic", "latin"],
  variable: "--font-open-sans", // CSS-переменная для Tailwind
})

export const metadata: Metadata = {
  title: "AI TG",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru" className={`${unbounded.variable} ${manrope.variable} ${openSans.variable} ${inter.variable}`}>
      <body className="flex flex-col min-h-screen">
        <DesktopGuard />

        <div className="hidden xl:flex flex-col min-h-screen grow">
          <Header />
          <main className="flex-1 flex flex-col">
            {children}
          </main>
          <Footer />
          <AnalysisModal />
        </div>
      </body>
    </html>
  );
}
