import type { Metadata } from "next";
import { Unbounded, Manrope, Open_Sans } from "next/font/google";
import "@/app/globals.css";

const unbounded = Unbounded({
  subsets: ["cyrillic", "latin"],
  variable: "--font-unbounded", // Создаем CSS-переменную
});

const manrope = Manrope({
  subsets: ["cyrillic", "latin"],
  variable: "--font-manrope",
});

const openSans = Open_Sans({
  subsets: ["cyrillic", "latin"],
  variable: "--font-open-sans", // CSS-переменная для Tailwind
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru" className={`${unbounded.variable} ${manrope.variable} ${openSans.variable}`}>
      <body>
        <div>
          <main>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}